### ISSUE TITLE
file-error on Windows

### ISSUE THREAD

**Issue by FelixHuoEZ** [kuanyui/tldr.el#17]
When I first use `tldr` or `tldr-update-docs`, Emacs give the following error.
Environment: Windows 7 x64, emacs 24.5.
```
﻿Debugger entered--Lisp error: (file-error "Renaming" "no such file or directory" "c:/emacs/.emacs.d/tldr-master" "c:/emacs/.emacs.d/tldr/")
  rename-file("~/.emacs.d/tldr-master" "~/.emacs.d/tldr/")
  tldr-update-docs()
  #<subr call-interactively>(tldr-update-docs record nil)
  ad-Advice-call-interactively(#<subr call-interactively> tldr-update-docs record nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (tldr-update-docs record nil))
  call-interactively(tldr-update-docs record nil)
  command-execute(tldr-update-docs record)
  #[257 "\304\305!\203\f" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"]("tldr-update-docs")
﻿  ivy-call()
  ivy-read("M-x " ("tldr-update-docs" "tldr" "cfs-switch-profile" "erc" "eval-region" "comment-region" "yas-visit-snippet-file" "eval-buffer" "replace-string" "package-list-packages" "ag" "uncomment-region" "cfs-edit-profile" "TeX-clean" "replace-regexp" "linum-mode" "org-mode" "shell" "query-replace-regexp" "figlet" "org2issue" "revert-buffer-with-coding-system" "org-ref" "scratch" "set-buffer-file-coding-system" "describe-coding-system" "emacs-lisp-mode" "yas-recompile-all" "org-do-demote" "eshell" "blog-admin-start" "yas-new-snippet" "uimage-display-images" "cfs-edit-profile-without-ui" "lispy-mode" "cfs-insert-fontname" "view-mode" "figlet-comment" "mc/mark-next-like-this-word" "indent-region" "tabbar-mode" "uimage-mode" "yas-reload-all" "pyim-dicts-manager" "shell-command" "string-insert-rectangle" "update-directory-autoloads" "gshell" "auto-fill-mode" "org-download-yank" ...) :predicate nil :require-match t :history extended-command-history :action #[257 "\304\305!\203\f" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"] :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input "^" :caller counsel-M-x)
  counsel-M-x()
  #<subr call-interactively>(counsel-M-x nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> counsel-M-x nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (counsel-M-x nil nil))
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
```

**Comment by kuanyui** [comment]
What's the directory name of the downloaded & extracted tldr files?

**Comment by FelixHuoEZ** [comment]
@kuanyui There is no tldr files in my local.
I did not set the directory, so maybe it is using the default directory.
In the error message, they are `~/.emacs.d/tldr-master` and `~/.emacs.d/tldr`.

**Comment by kuanyui** [comment]
Sorry for late, work is too busy.
I mean, check your ~/.emacs.d/ and see if there's any directory or zip file looks like tldr.el had downloaded?
I want to know if the zip file is really downloaded.

**Comment by FelixHuoEZ** [comment]
@kuanyui There is no such kind of folder or zip file. I search it with `Everything` on Windows.

**Comment by kuanyui** [comment]
I got it. Your system has no `unzip` installed, and my checking mechanism has flaw. Now should be fixed.

**Comment by FelixHuoEZ** [comment]
I try it, but the problem still exists.
I test `unzip` in `cmd`, and it works well, so maybe it's not the reason.

**Comment by kuanyui** [comment]
!!!
Is your unzip in the PATH of Emacs? `M-! unzip` too see what happened.

**Comment by FelixHuoEZ** [comment]
@kuanyui It also works well. Shell Command Output is as follows.
```sh
UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.

Usage: unzip [-Z] [-opts[modifiers]] file[.zip] [list] [-x xlist] [-d exdir]
  Default action is to extract files in list, except those in xlist, to exdir;
  file[.zip] may be a wildcard.  -Z => ZipInfo mode ("unzip -Z" for usage).

  -p  extract files to pipe, no messages     -l  list files (short format)
  -f  freshen existing files, create none    -t  test compressed archive data
  -u  update files, create if necessary      -z  display archive comment only
  -v  list verbosely/show version info       -T  timestamp archive to latest
  -x  exclude files that follow (in xlist)   -d  extract files into exdir
modifiers:
  -n  never overwrite existing files         -q  quiet mode (-qq => quieter)
  -o  overwrite files WITHOUT prompting      -a  auto-convert any text files
  -j  junk paths (do not make directories)   -aa treat ALL files as text
  -C  match filenames case-insensitively     -L  make (some) names lowercase
  -$  label removables (-$$ => fixed disks)  -V  retain VMS version numbers
  -X  restore ACLs (-XX => use privileges)   -s  spaces in filenames => '_'
                                             -M  pipe through "more" pager
See "unzip -hh" or unzip.txt for more help.  Examples:
  unzip data1 -x joe   => extract all files except joe from zipfile data1.zip
  unzip -fo foo ReadMe => quietly replace existing ReadMe if archive file newer
```

**Comment by kuanyui** [comment]
How did you install unzip? I may try to do the same thing under Windows VM....

**Comment by FelixHuoEZ** [comment]
There are sevaral `unzip` location in the system environment variable `PATH`, which are as follows. So it just came with other software.
```sh
C:\Users\Administrator>where unzip
C:\texlive\2016\bin\win32\unzip.exe
C:\ProgramData\chocolatey\bin\unzip.exe
C:\Program Files\Git\usr\bin\unzip.exe
C:\Users\Administrator\.babun\cygwin\bin\unzip.exe
```

**Comment by kuanyui** [comment]
Please check your email inbox
